### ISSUE TITLE
Don't probe for fstar.exe when the input file is JSON

### ISSUE THREAD

**Issue by BarryBo** [FStarLang/kremlin#10]
This will reduce a tool dependency when extracting C from Dafny.

"Fatal error: exception Failure("Did not find fstar.exe in the PATH")"

**Comment by msprotz** [comment]
If you intend to run the compiler yourself, you can use -skip-compilation in the meanwhile and it won't try to detect F* provided the input file is JSON. I'll refactor that bit to make it behave better (we do need to detect the kremlin home to drive the C compiler, in order to provide proper `-I` files).
