### ISSUE TITLE
Inconsistent declarations for FStar.UInt.min_int

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/kremlin#119]
I keep getting inconsistent declarations for `FStar.UInt.max_int`, see below. I wasn't able to figure whether that's a problem in the source or in Kremlin, but since it used to work, I guess it depends on something that changed recently. 

```
cc -O3 -march=native -mtune=native -funroll-loops -I /mnt/e/everest/joonwonc_merkle_tree/kremlin/include -I /mnt/e/everest/joonwonc_merkle_tree/kremlin/kremlib -I /mnt/e/everest/joonwonc_merkle_tree/hacl-star/lib -Wall -Wextra -Werror -Wno-parentheses -Wno-unused-parameter -Wno-unused-variable -Wno-infinite-recursion   -c -o c/FStar.o c/FStar.c
c/FStar.c:14:18: error: static declaration of ‘FStar_UInt_min_int’ follows non-static declaration
 static Prims_int FStar_UInt_min_int(Prims_int n)
                  ^~~~~~~~~~~~~~~~~~
In file included from /mnt/e/everest/joonwonc_merkle_tree/kremlin/kremlib/extracted/TestLib.h:14:0,
                 from c/Prims.h:12,
                 from c/FStar.h:11,
                 from c/FStar.c:7:
/mnt/e/everest/joonwonc_merkle_tree/kremlin/kremlib/extracted/FStar_UInt.h:20:11: note: previous declaration of ‘FStar_UInt_min_int’ was here
 Prims_int FStar_UInt_min_int(Prims_int n);
           ^~~~~~~~~~~~~~~~~~
cc1: error: unrecognized command line option ‘-Wno-infinite-recursion’ [-Werror]
cc1: all warnings being treated as errors
<builtin>: recipe for target 'c/FStar.o' failed
make[2]: *** [c/FStar.o] Error 1
```

(It's easy to fix post-hoc, but I'd rather have the actual problem resolved.)

**Comment by msprotz** [comment]
hello Christoph,

It seems like some files that come from two different invocations of kremlin are being included in the same scope. This is unsupported. If I had to make a wild guess, I would suspect you have two different TestLib.h, one that is in c/ and another one that is in kremlib/, and that compiling `c/FStar.c` ends up including `kremlib/TestLib.h` instead of `c/TestLib.h`.

Can you compile the contents of `c` and `kremlib` separately, without exposing one to the other on the include path? That should help identifying the build error.

Thanks,

Jonathan

**Comment by wintersteiger** [comment]
Hmm, actually, I don't think that was the case. I was using kremlib via the Merkle trees and I tried to reuse as much as possible of that so I don't have to have a second copy. I don't think I need `TestLib.h` though, so maybe I'll just exclude that from the snapshot.

**Comment by msprotz** [comment]
The new snapshot of Merkle trees does not include TestLib.h after my latest merge. This should solve it.
