### ISSUE TITLE
Use standard OCaml CI scripts

### ISSUE THREAD

**Issue by XVilka** [FStarLang/kremlin#140]
See https://github.com/ocaml/ocaml-ci-scripts
It will help to keep track of various OCaml/opam switches, and will relieve some workarounding efforts. So adding a new version in the build matrix would be very easy as adding a new line:
```yaml
env:
  - OCAML_VERSION=4.02 [...]
  - OCAML_VERSION=4.05 [...]
  - OCAML_VERSION=4.07 [...]
  - OCAML_VERSION=4.08 [...]
```
See https://github.com/ocaml/ocaml-ci-scripts/blob/master/README-travis.md

**Comment by msprotz** [comment]
thanks for the bug report! we switched away from travis to use azure pipelines recently, where we are able to get machines with much more capacity. Since Kremlin CI requires building F*, we are now able to get 2min turnaround times via our in-house docker container infrastructure, as opposed to 45+ min CI times previously

**Comment by msprotz** [comment]
I removed the last config file that remained from the travis era
