### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by rrika** [FStarLang/kremlin#17]
This is probably a setup problem on my side but maybe you know why it happens?
I built f* master (22a1d1b049e63666c227815f40ea5178c9ea58f1), and then with fstar.exe in PATH I built kremlin.
Now, running "make test" fails. Specifically:

    ~/src/fstar/bin/fstar.exe --odir Hoisting.out --codegen Kremlin --lax --no_extract FStar.Math.Lib --no_extract FStar.HyperHeap --no_extract FStar.HyperStack --no_extract FStar.ST --no_extract FStar.Seq --no_extract FStar.UInt128 --no_extract FStar.Int128 --no_extract FStar.UInt64 --no_extract FStar.Int64 --no_extract FStar.UInt63 --no_extract FStar.Int63 --no_extract FStar.UInt32 --no_extract FStar.Int32 --no_extract FStar.UInt31 --no_extract FStar.Int31 --no_extract FStar.UInt16 --no_extract FStar.Int16 --no_extract FStar.UInt8 --no_extract FStar.Int8 --trace_error --include ~/src/fstar/ulib/hyperstack --include ~/src/fstar/examples/low-level/crypto --include ~/src/fstar/examples/low-level/crypto/real --include . --include ~/src/kremlin/kremlib Hoisting.fst

fails with

    ./TestLib.fsti(22,9-22,64) : (Error) Constructor FStar.HyperStack not found

**Comment by msprotz** [comment]
KreMLin hasn't been kept up to date with the latest F* changes -- we're trying to get all of the projects in sync (F*, miTLS & KreMLin) with a better testing infrastructure so that people like you can easily check out all of the projects and get a set of revisions that work well together. Sorry for the mess! Hopefully it'll be sorted out by the end of this week.

Can you try with the F* branch called c_record_aead?

**Comment by rrika** [comment]
That works. Thank you.
