### ISSUE TITLE
kremlib.h:  __int128 type not supported by Microsoft C compiler

### ISSUE THREAD

**Issue by BarryBo** [FStarLang/kremlin#2]
"typedef __int128 FStar_UInt128_t, FStar_UInt128_t_;" doesn't compile.  There is no support for generic 128-bit math.  The _m128 type can be used to generate 128-bit MMX code though.

**Comment by msprotz** [comment]
The only toolchain that I've tested is clang & gcc (including mingw). I think @jkzinzindohoue has been using 128-bit integers to implement the faster algorithms for elliptic curves, so it seems like he does need this type.

Any suggestions if we want to support to the Microsoft toolchain? I assume that this is not going to be the only problem, since I'm using a bunch of C99 features (e.g. field initializers, fixed-width int macros)...

Actually, it seems like the 2013 version includes most of these, so int128 might be the only issue so far (see http://stackoverflow.com/questions/9610747/which-c99-features-are-available-in-the-ms-visual-studio-compiler)

**Comment by msprotz** [comment]
It seems like an #ifdef that uses `_m128` if MSVC, `__int128` otherwise would be good. Or perhaps a configure script or something along those lines.

**Comment by BarryBo** [comment]
VS2015 64-bit C compiler still doesn’t support it…

C:\Repos\Spartan>cl /c DafnyDefaultModule.c /I ..\kremlin\kremlib
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24213.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

DafnyDefaultModule.c
..\kremlin\kremlib\kremlib.h(15): error C4235: nonstandard extension used: '__int128' keyword not supported on this architecture

“long long” is 64-bit in the Microsoft compiler… an alias for “long”.


_m128 is not a drop-in replacement, as that datatype has very different operators than C integers.  They represent SSE registers, so you have to emit explicit load and store code, and you’d have to implement your own 128-bit integer math on top, as they operate either on 128-bit bitfields, or pairs of 64-bit integers.

For the 128-it crypto code, the ultimate code-gen is most likely a pair of 64-bit values, both in registers and in memory, with explicit code to do carries and borrows between the two halves.  It would probably be better for the EC code to do that explicit math itself, instead of depending on the C compiler’s nonstandard support.

Barry

**Comment by msprotz** [comment]
I agree that it's suboptimal. Let me chat with @jkzinzindohoue to figure out whether he truly needs it or whether he can get away with it once I support pairs.

**Comment by jkzinzindohoue** [comment]
I truly need it. These are not just pairs since they support all standard integer operations. I don't think it is reasonable to pay the cost of reimplementing everything and not benefit from clang and GCC's optimizations.
Similarly I don't want to reimplement the curves on 64bits integers, there would be significant changes to the proof.
Why not just disabling int128s and the curve compilation when using the MS compiler ?

**Comment by msprotz** [comment]
We can start having compiler-specific support libraries; Kremlin emits FStar_Int128_addition; the gcc/clang support library uses +; the msvc support library uses whatever textbook algorithm is used for 128-bit addition using two long longs.

**Comment by BarryBo** [comment]
Microsoft C compiler implements “long long” as 64-bit only.  There is no 128-bit integer type in the compiler or runtime.

See https://msdn.microsoft.com/en-us/library/s3f49ktz.aspx

**Comment by msprotz** [comment]
Sorry, I meant implement uint128_t using a struct with two long longs, then implement arithmetic "by hand" based on that.

**Comment by msprotz** [comment]
3dda050 should work around the issue but we still need to determine what we intend to do if we want to support @jkzinzindohoue's code with MSVC

**Comment by msprotz** [comment]
@jkzinzindohoue just provided an implementation for int128s that works with Compcert and, mostly, the Microsoft C compiler.

**Comment by jkzinzindohoue** [comment]
To be precise, it provides an implementation for addition, subtraction and bitwise operators. I think they follow our constant time discipline (see [custom128.c](https://github.com/FStarLang/kremlin/blob/master/kremlib/custom128.c)).
There is also support to multiply two uint64 to get a uint128, and casts back and forth from uint64 to uint128. But no more (because I do not need more for now).
