### ISSUE TITLE
Feature request:  re-order type declarations towards the top of the generated .h files

### ISSUE THREAD

**Issue by BarryBo** [FStarLang/kremlin#4]
Dafny compiles modules and within modules, top-level declarations, in no particular order.   Kremlin preserves this order found in the AST.  This leads to problems where a type is referenced before it has been defined, causing a C compiler error.

I am approximating a dependency graph in Dafny by delaying generation of the default module and the default class until last.  That helps, but not enough, as non-default classes depend on other non-default classes too.

I suspect that Kremlin will need to generate a full type dependency graph, and generate code that order.  The other alternative is to try making a pre-pass over DTypeFlat and DTypeAlias, to emit C declarations.  Then go back and generate C definitions for all decls afterwards.

**Comment by msprotz** [comment]
Yes. I remember thinking about it, and concluding that F\* topologically orders modules before passing them to Kremlin, which solves the problem.

I could implement a topological sort (optional) in Kremlin for the Dafny use-case... if you guarantee that there is no mutual recursion between modules (as C allows) and between functions within the same module. The topological sort would sort modules and for each module would sort the top-level declarations.

Otherwise, I'll add an option that:
- includes every .h (to solve cross-module dependency)
- declares every function prototype at the beginning of a file in a .c file (to solve mutually recursive functions).

Alternatively, if it's easier to perform at the Dafny level, you could consider doing that before handing it out to Kremlin.

**Comment by BarryBo** [comment]
Let me try from the Dafny side.

I find a way to extract modules in topological order already.  Types within modules should also be available, possibly only in an earlier stage in the compiler, but something I can cause to be reconstructed when I need it.

Barry

**Comment by BarryBo** [comment]
I just committed a change (59ac5d8acccf8b2890fe4fb06d5b9e1f37ab9fe9) to Dafny that completes this work.  The modules are now generated in dependency order, and within each module, types are generated in dependency order.

No work needs to be done in Kremlin.
